// @ts-nocheck
import React from 'react';
import { THEME_OPTIONS } from '../decorations';
import { T_Quote, T_Stat, T_Announce, T_Steps, T_BeforeAfter, T_Manifesto, T_Checklist, T_Opinion, T_Pillars } from './single';
import { V_Framework, V_Story, V_TipsCarousel, V_MistakesMade, V_MiniGuide } from './carousel';
import { T_Booking, T_LinkBio, T_Launch, T_Waitlist, T_LeadMagnet, T_DMKeyword } from './cta';
import { T_BreakingPost, T_WeeklyDigest, T_NewsHero, T_NewsSplit, T_NewsInterview } from './news';
import { T_PhotoPost, T_WorkShowcase, T_Team1, T_Team2, T_Team3, T_Team4 } from './photo';
import { T_PricingCard, T_Pricing3Tier, T_PricingRetainer, T_PricingAudit, T_TestimonialEditorial } from './pricing';
import { T_Testimonial, T_PricingEditorial, T_MetricProof, T_TweetReview, T_CaseStudy } from './socialProof';

/* ============ Template registry ============ */
const f = (key, label, opts = {}) => ({ key, label, type: opts.type || "text", placeholder: opts.placeholder, hint: opts.hint });
const fA = (key, label, opts = {}) => f(key, label, { type: "textarea", ...opts });

const SocialTemplates = [
  /* --- Single (Instagram 1:1) --- */
  { id: "quote",        name: "Pull Quote",        kind: "Single",
    slides: (p) => [<T_Quote {...p} />],
    fields: [
      f("label", "Top-right label"),
      fA("quote", "Quote"),
      f("role", "Role pill", { placeholder: "Director" }),
      f("attribution", "Name pill"),
    ] },
  { id: "stat",         name: "Stat Hero",         kind: "Single",
    slides: (p) => [<T_Stat {...p} />],
    fields: [
      f("kicker", "Kicker"),
      f("italicLead", "Italic lead-in", { placeholder: "Why do most posts fail?" }),
      f("stat", "Stat", { placeholder: "91%" }),
      fA("statLabel", "Statement"),
    ] },
  { id: "announce",     name: "Announcement",      kind: "Single",
    slides: (p) => [<T_Announce {...p} />],
    fields: [
      f("label", "Bracket label"),
      f("headlineA", "Headline · roman"),
      f("headlineB", "Headline · italic"),
    ] },
  { id: "steps",        name: "Process",           kind: "Single",
    slides: (p) => [<T_Steps {...p} />],
    fields: [
      f("kicker", "Top-left label", { placeholder: "Method" }),
      fA("headline", "Headline (the word to circle goes in the next field)"),
      f("circled", "Word to circle in red", { placeholder: "POSTS" }),
      f("pillLeft", "Bottom-left pill"),
      f("pillRight", "Top-right pill"),
      fA("note", "Italic note · bottom-right"),
    ] },
  { id: "ba",           name: "Before / After",    kind: "Single",
    slides: (p) => [<T_BeforeAfter {...p} />],
    fields: [
      f("beforeSubtitle", "Before — subtitle", { placeholder: "The way most freelancers work." }),
      fA("before", "Before — headline"),
      f("beforeNote", "Before — mono note"),
      f("afterSubtitle", "After — subtitle", { placeholder: "The way our system works." }),
      fA("after", "After — headline"),
      f("afterNote", "After — mono note"),
    ] },
  { id: "manifesto",    name: "Manifesto",         kind: "Single",
    slides: (p) => [<T_Manifesto {...p} />],
    fields: [
      f("kicker", "Kicker"),
      f("lead", "Lead · roman", { placeholder: "Tech that" }),
      f("italic", "Italic word/phrase", { placeholder: "just works." }),
      fA("tail", "Trailing sentence (muted)"),
    ] },
  { id: "checklist",    name: "Quick Audit",       kind: "Single",
    slides: (p) => [<T_Checklist {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Audit Checklist" }),
      f("title", "Checklist title", { placeholder: "5 Things to check before sending an invoice" }),
      fA("items", "Items (one per line, up to 5)", { hint: "Add 3–5 items." }),
      f("note", "Bottom note", { placeholder: "Save this post for your next project" }),
    ] },
  { id: "opinion",      name: "Myth vs Reality",   kind: "Single",
    slides: (p) => [<T_Opinion {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Reality Check" }),
      f("mythTitle", "Myth label", { placeholder: "Myth" }),
      fA("myth", "Myth statement"),
      f("truthTitle", "Reality label", { placeholder: "Reality" }),
      fA("truth", "Reality statement"),
    ] },
  { id: "pillars",      name: "Core Pillars",      kind: "Single",
    slides: (p) => [<T_Pillars {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Core Principles" }),
      f("headline", "Headline", { placeholder: "The 3 Pillars of High-Earning Freelancers" }),
      f("pillar1Title", "Pillar 01 Title", { placeholder: "Positioning" }),
      f("pillar1Body", "Pillar 01 Description"),
      f("pillar2Title", "Pillar 02 Title", { placeholder: "Packaging" }),
      f("pillar2Body", "Pillar 02 Description"),
      f("pillar3Title", "Pillar 03 Title", { placeholder: "Pipeline" }),
      f("pillar3Body", "Pillar 03 Description"),
    ] },

  /* --- Carousel --- */
  { id: "framework",    name: "Framework",         kind: "Carousel",
    slides: (p) => T_Framework(p),
    fields: [
      f("title", "Title (cover)"),
      f("subtitle", "Subtitle (cover)"),
      f("coverLabel", "Cover bracket label", { placeholder: "A Framework" }),
      fA("steps", "Steps — 'Name — body', one per line", { hint: "One step per line. No hard limit." }),
      f("ctaText", "Closing slide CTA text (optional)", { hint: "Leave empty to skip the closing slide." }),
    ] },
  { id: "story",        name: "Short Story",       kind: "Carousel",
    slides: (p) => T_Story(p),
    fields: [
      f("kicker", "Cover kicker", { placeholder: "A Short Story" }),
      f("coverLead", "Cover · roman"),
      f("coverItalic", "Cover · italic"),
      fA("slides", "Story slides — 'Kicker — Body', one per line", { hint: "Colors cycle cream → blue → lime → ink. Add as many slides as needed." }),
      f("ctaText", "Closing slide CTA text (optional)", { hint: "Leave empty to skip the closing slide." }),
    ] },
  { id: "tipscarousel", name: "Tips Carousel",     kind: "Carousel",
    slides: (p) => T_Tips(p),
    fields: [
      f("kicker", "Kicker"),
      f("ruleLabel", "Slide label word", { placeholder: "Rule", hint: "Appears as 'Rule 1 of N'. Change to Tip, Lesson, Step…" }),
      f("titleItalic", "Cover italic line", { placeholder: "I keep close." }),
      fA("subtitle", "Subtitle (cover)"),
      fA("tips", "Tips (one per line)", { hint: "Add as many as needed — no limit." }),
      f("ctaText", "Closing slide CTA text (optional)", { hint: "Leave empty to skip the closing slide." }),
    ] },
  { id: "mistakes",    name: "Mistakes Made",      kind: "Carousel",
    slides: (p) => T_Mistakes(p),
    fields: [
      f("kicker", "Kicker", { placeholder: "Hard Lessons" }),
      f("titleItalic", "Cover italic title", { placeholder: "I made for you." }),
      fA("subtitle", "Cover subtitle"),
      fA("mistakes", "Mistakes — 'Title — Lesson', one per line", { hint: "No limit. Title is bold; lesson appears as italic note." }),
      f("ctaText", "Closing CTA text (optional)", { hint: "Leave empty to skip the closing slide." }),
    ] },
  { id: "miniguide",   name: "Mini Guide",          kind: "Carousel",
    slides: (p) => T_MiniGuide(p),
    fields: [
      f("kicker", "Kicker", { placeholder: "Mini Guide" }),
      f("prefix", "Top prefix label", { placeholder: "How to" }),
      f("topic", "Topic / title", { placeholder: "Ship Faster" }),
      f("intro", "Cover intro line", { hint: "Leave empty to auto-generate from step count." }),
      fA("steps", "Steps — 'Name — detail', one per line", { hint: "Detail is optional. No slide limit." }),
      f("ctaText", "Closing CTA text (optional)", { hint: "Leave empty to skip the closing slide." }),
    ] },

  /* --- CTA --- */
  { id: "booking",      name: "Now Booking",       kind: "CTA",
    slides: (p) => [<T_Booking {...p} />],
    fields: [
      f("label", "Top-left label", { placeholder: "Now Booking" }),
      f("lead", "Lead-in", { placeholder: "Two spots open for" }),
      f("window", "Window (circled)", { placeholder: "Q3" }),
      f("project", "Accent / Trailing text", { placeholder: "projects." }),
      fA("subtext", "Subtext"),
      f("ctaText", "CTA text"),
    ] },
  { id: "linkbio",      name: "Link-in-bio",       kind: "CTA",
    slides: (p) => [<T_LinkBio {...p} />],
    fields: [
      f("label", "Top label"),
      f("kicker", "Kicker"),
      f("headlineA", "Headline · roman"),
      f("headlineB", "Headline · italic"),
      fA("subtext", "Subtext"),
      f("url", "URL / path"),
    ] },
  { id: "launch",       name: "Launch",            kind: "CTA",
    slides: (p) => [<T_Launch {...p} />],
    fields: [
      f("kicker", "Top-left label", { placeholder: "Launching" }),
      f("category", "Category"),
      f("productName", "Product name"),
      fA("tagline", "Tagline"),
      f("date", "Launch date"),
      f("ctaText", "CTA text"),
    ] },
  { id: "waitlist",     name: "Waitlist",          kind: "CTA",
    slides: (p) => [<T_Waitlist {...p} />],
    fields: [
      f("kicker", "Kicker", { placeholder: "Early Access" }),
      f("spotsLeft", "Spots badge", { placeholder: "4 spots left" }),
      fA("headline", "Main headline", { placeholder: "The new way to build freelance proposals" }),
      fA("subtext", "Subtext"),
      f("ctaText", "CTA button text", { placeholder: "Join the waitlist →" }),
    ] },
  { id: "leadmagnet",   name: "Free Resource",     kind: "CTA",
    slides: (p) => [<T_LeadMagnet {...p} />],
    fields: [
      f("category", "Top label", { placeholder: "Free Resource" }),
      f("deliverableType", "Format pill", { placeholder: "PDF + Notion Sheet" }),
      fA("title", "Resource title", { placeholder: "The 2026 Freelance Rate & Pricing Guide" }),
      fA("benefits", "Included benefits (one per line, up to 4)"),
      f("ctaText", "CTA button text", { placeholder: "Download free copy →" }),
    ] },
  { id: "dmkeyword",    name: "DM Keyword",        kind: "CTA",
    slides: (p) => [<T_DMKeyword {...p} />],
    fields: [
      f("kicker", "Top-left kicker", { placeholder: "Free Drop" }),
      fA("headline", "Question / hook", { placeholder: "Want my Notion Client Onboarding Portal?" }),
      f("keyword", "Comment keyword", { placeholder: "ONBOARD" }),
      f("resourceName", "Resource name in footnote", { placeholder: "the Notion template link" }),
    ] },

  /* --- Social Proof --- */
  { id: "testimonial", name: "Testimonial Card",    kind: "Social Proof",
    slides: (p) => [<T_TestimonialEditorial {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Client proof" }),
      fA("quote", "Quote"),
      f("clientName", "Client name"),
      f("clientTitle", "Client title / company", { placeholder: "Founder · Atlas & Bell" }),
      { key: "clientPhoto", label: "Client photo (optional)", type: "image" },
    ] },
  { id: "metricproof", name: "Metric Impact",       kind: "Social Proof",
    slides: (p) => [<T_MetricProof {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Client Results" }),
      f("metric", "Big metric number", { placeholder: "+240%" }),
      fA("metricLabel", "Metric description / timeframe", { placeholder: "Increase in closed deal size in 60 days" }),
      fA("summary", "Context / engagement summary"),
      f("clientName", "Client name", { placeholder: "Sarah Jenkins" }),
      f("clientRole", "Client role & company", { placeholder: "Managing Director · Apex" }),
    ] },
  { id: "tweetreview", name: "Social Review",       kind: "Social Proof",
    slides: (p) => [<T_TweetReview {...p} />],
    fields: [
      f("kicker", "Kicker", { placeholder: "Client Feedback" }),
      fA("review", "Review quote"),
      f("clientName", "Client name", { placeholder: "Alex Rivera" }),
      f("handle", "Social handle", { placeholder: "@alexrivera_" }),
      f("clientTitle", "Role or company", { placeholder: "Founder" }),
    ] },
  { id: "casestudy",   name: "Case Study Snapshot", kind: "Social Proof",
    slides: (p) => [<T_CaseStudy {...p} />],
    fields: [
      f("kicker", "Kicker", { placeholder: "Case Study" }),
      f("client", "Client name / project", { placeholder: "Luminary Media" }),
      f("industry", "Industry & year", { placeholder: "Design & Tech · 2026" }),
      fA("problem", "The Problem"),
      fA("solution", "The Solution"),
      fA("outcome", "The Result"),
    ] },

  /* --- News --- */
  { id: "breaking",    name: "Breaking Post",       kind: "News",
    slides: (p) => [<T_BreakingPost {...p} />],
    fields: [
      f("category", "Top-bar category", { placeholder: "Industry" }),
      f("date", "Date", { placeholder: "May · 2026" }),
      f("kicker", "Kicker label", { placeholder: "Breaking" }),
      f("headline", "Headline"),
      f("subline", "Subline · italic (optional)"),
      fA("body", "Body copy (optional)"),
    ] },
  { id: "digest",      name: "Weekly Digest",       kind: "News",
    slides: (p) => [<T_WeeklyDigest {...p} />],
    fields: [
      f("period", "Period label", { placeholder: "This Week In" }),
      f("topic", "Topic", { placeholder: "Design" }),
      fA("items", "Items (one per line)", { hint: "3–5 items works best." }),
    ] },
  { id: "newshero",    name: "News Hero Photo",     kind: "News",
    slides: (p) => [<T_NewsHero {...p} />],
    fields: [
      f("category", "Category pill", { placeholder: "Report" }),
      f("date", "Date label", { placeholder: "May 2026" }),
      { key: "image", label: "Featured Photo", type: "image" },
      f("tag", "Photo overlay tag (optional)", { placeholder: "Exclusive" }),
      f("headline", "News headline", { placeholder: "Freelance studios win 75% of new tech branding briefs" }),
      fA("synopsis", "Editorial synopsis / summary"),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
  { id: "newssplit",   name: "News Split 50/50",    kind: "News",
    slides: (p) => [<T_NewsSplit {...p} />],
    fields: [
      f("category", "Category pill", { placeholder: "Press" }),
      { key: "image", label: "Portrait Photo", type: "image" },
      f("kicker", "Kicker label", { placeholder: "Industry Dispatch" }),
      f("headline", "Headline", { placeholder: "The shift towards asynchronous studio retainers" }),
      fA("takeaways", "Key takeaways (one per line, up to 3)"),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
  { id: "newsinterview", name: "News Spotlight",   kind: "News",
    slides: (p) => [<T_NewsInterview {...p} />],
    fields: [
      f("kicker", "Kicker pill", { placeholder: "Founder Spotlight" }),
      f("publication", "Publication / Issue tag", { placeholder: "Issue No. 12" }),
      { key: "image", label: "Portrait Photo", type: "image" },
      f("speaker", "Speaker Name", { placeholder: "Marcus Bell" }),
      f("title", "Speaker Title", { placeholder: "Managing Partner" }),
      fA("quote", "Pull quote statement"),
      f("context", "Quote source / context", { placeholder: "On the future of document design" }),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },

  /* --- Photo --- */
  { id: "photopost",   name: "Photo Post",          kind: "Photo",
    slides: (p) => [<T_PhotoPost {...p} />],
    fields: [
      { key: "image", label: "Photo", type: "image" },
      f("tag", "Tag / category label (optional)"),
      fA("caption", "Caption"),
    ] },
  { id: "showcase",    name: "Work Showcase",       kind: "Photo",
    slides: (p) => [<T_WorkShowcase {...p} />],
    fields: [
      { key: "image", label: "Project photo", type: "image" },
      f("client", "Client name"),
      f("projectType", "Project type", { placeholder: "Brand" }),
      f("year", "Year", { placeholder: "2026" }),
      fA("tagline", "Project tagline"),
    ] },
  { id: "team1",       name: "Team Onboard · Single", kind: "Photo",
    slides: (p) => [<T_Team1 {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Welcome to the Team" }),
      { key: "image", label: "Member Photo", type: "image" },
      f("badge", "Pill Badge (e.g. New Joiner, Top Performer, Best Achiever)", { placeholder: "New Joiner" }),
      f("name", "Member Name", { placeholder: "Elena Rostova" }),
      f("position", "Position / Role", { placeholder: "Lead Brand Designer" }),
      f("department", "Department / Location (optional)", { placeholder: "Brand Studio · London" }),
      fA("bio", "Short Welcome Note (optional)", { placeholder: "Joining our studio to lead brand identity and digital design systems." }),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
  { id: "team2",       name: "Team Onboard · Duo",    kind: "Photo",
    slides: (p) => [<T_Team2 {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "New Joiners" }),
      f("headline", "Headline", { placeholder: "Welcoming two new leads to the studio" }),
      { key: "image1", label: "Member 1 Photo", type: "image" },
      f("name1", "Member 1 Name", { placeholder: "Marcus Vance" }),
      f("position1", "Member 1 Position", { placeholder: "Creative Director" }),
      { key: "image2", label: "Member 2 Photo", type: "image" },
      f("name2", "Member 2 Name", { placeholder: "Aria Chen" }),
      f("position2", "Member 2 Position", { placeholder: "Senior Engineer" }),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
  { id: "team3",       name: "Team Onboard · Trio",   kind: "Photo",
    slides: (p) => [<T_Team3 {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Meet the Crew" }),
      f("headline", "Headline", { placeholder: "Meet the new faces at the studio" }),
      { key: "image1", label: "Member 1 Photo", type: "image" },
      f("name1", "Member 1 Name", { placeholder: "Sophia Ray" }),
      f("position1", "Member 1 Position", { placeholder: "Design Lead" }),
      { key: "image2", label: "Member 2 Photo", type: "image" },
      f("name2", "Member 2 Name", { placeholder: "Liam Thorne" }),
      f("position2", "Member 2 Position", { placeholder: "Staff Engineer" }),
      { key: "image3", label: "Member 3 Photo", type: "image" },
      f("name3", "Member 3 Name", { placeholder: "Maya Patel" }),
      f("position3", "Member 3 Position", { placeholder: "Product Strategist" }),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
  { id: "team4",       name: "Team Onboard · Quad",   kind: "Photo",
    slides: (p) => [<T_Team4 {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Team Expansion" }),
      f("headline", "Headline", { placeholder: "Welcoming 4 new team members" }),
      { key: "image1", label: "Member 1 Photo", type: "image" },
      f("name1", "Member 1 Name", { placeholder: "Elena Rostova" }),
      f("position1", "Member 1 Position", { placeholder: "Brand Lead" }),
      { key: "image2", label: "Member 2 Photo", type: "image" },
      f("name2", "Member 2 Name", { placeholder: "Marcus Vance" }),
      f("position2", "Member 2 Position", { placeholder: "Creative Director" }),
      { key: "image3", label: "Member 3 Photo", type: "image" },
      f("name3", "Member 3 Name", { placeholder: "Aria Chen" }),
      f("position3", "Member 3 Position", { placeholder: "Staff Engineer" }),
      { key: "image4", label: "Member 4 Photo", type: "image" },
      f("name4", "Member 4 Name", { placeholder: "Sophia Ray" }),
      f("position4", "Member 4 Position", { placeholder: "Product Strategist" }),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },

  /* --- Pricing --- */
  { id: "pricing",     name: "Pricing Card",        kind: "Pricing",
    slides: (p) => [<T_PricingEditorial {...p} />],
    fields: [
      f("kicker", "Proposal / kicker label", { placeholder: "Proposal No. 01" }),
      f("packageName", "Package name", { placeholder: "Brand Starter" }),
      f("price", "Price (number only)", { placeholder: "1500" }),
      { key: "currency", label: "Currency", type: "select", options: [{ value: "USD", label: "USD ($)" }, { value: "IDR", label: "IDR (Rp)" }, { value: "EUR", label: "EUR (€)" }, { value: "GBP", label: "GBP (£)" }] },
      fA("features", "Features (one per line, 4–6 lines)"),
      f("ctaText", "CTA text", { placeholder: "DM to get started →" }),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
  { id: "pricing3tier", name: "Pricing 3-Tier Grid", kind: "Pricing",
    slides: (p) => [<T_Pricing3Tier {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Investment & Plans" }),
      f("headline", "Headline", { placeholder: "Transparent packages for every project stage" }),
      f("tier1Name", "Tier 1 Name", { placeholder: "Starter" }),
      f("tier1Price", "Tier 1 Price", { placeholder: "$1,200" }),
      f("tier1Desc", "Tier 1 Subtitle", { placeholder: "Essential brand basics" }),
      fA("tier1Features", "Tier 1 Features (one per line, up to 4)"),
      f("tier2Name", "Tier 2 Name (Popular)", { placeholder: "Pro Package" }),
      f("tier2Price", "Tier 2 Price", { placeholder: "$3,500" }),
      f("tier2Desc", "Tier 2 Subtitle", { placeholder: "Full identity & system" }),
      fA("tier2Features", "Tier 2 Features (one per line, up to 5)"),
      f("tier3Name", "Tier 3 Name", { placeholder: "Partner" }),
      f("tier3Price", "Tier 3 Price", { placeholder: "$6,000" }),
      f("tier3Desc", "Tier 3 Subtitle", { placeholder: "Custom end-to-end" }),
      fA("tier3Features", "Tier 3 Features (one per line, up to 5)"),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
  { id: "pricingretainer", name: "Pricing Retainer", kind: "Pricing",
    slides: (p) => [<T_PricingRetainer {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Studio Retainer" }),
      f("availability", "Availability badge", { placeholder: "2 Spots Available for Q3" }),
      f("packageName", "Package name", { placeholder: "Dedicated Design Partner" }),
      f("rate", "Monthly rate", { placeholder: "$4,500" }),
      f("tagline", "Tagline / Value proposition"),
      fA("deliverables", "Included deliverables (one per line, up to 5)"),
      f("ctaText", "CTA button text", { placeholder: "Inquire via DM →" }),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
  { id: "pricingaudit", name: "Pricing Audit / Sprint", kind: "Pricing",
    slides: (p) => [<T_PricingAudit {...p} />],
    fields: [
      f("kicker", "Kicker label", { placeholder: "Fixed-Scope Sprint" }),
      f("duration", "Duration pill", { placeholder: "2-Week Turnaround" }),
      f("headline", "Sprint Title", { placeholder: "Proposal & Document Teardown" }),
      f("price", "Flat fee", { placeholder: "$1,800" }),
      fA("deliverables", "Deliverables checklist (one per line, up to 4)"),
      f("ctaText", "Booking button text", { placeholder: "Book Sprint →" }),
      { key: "bg", label: "Theme", type: "select", options: THEME_OPTIONS },
    ] },
];

export { SocialTemplates };
